# Generated by Django 3.1.4 on 2021-11-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='number_bedroom',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='number_private_bathroom',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='number_shared_bathroom',
        ),
    ]
