# Generated by Django 3.1.4 on 2021-11-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_auto_20211101_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='number_bedroom_with_private_bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='number_bedroom_without_bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='number_shared_bathroom',
            field=models.IntegerField(default=0),
        ),
    ]
