# Generated by Django 3.2.9 on 2021-11-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_auto_20211112_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='number_bedroom_with_private_bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='number_bedroom_without_bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='number_shared_bathroom',
            field=models.IntegerField(default=0),
        ),
    ]
