# Generated by Django 3.2.9 on 2021-11-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_auto_20211112_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='number_bedroom_with_private_bathroom',
            new_name='number_bedroom',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='number_bedroom_without_bathroom',
            new_name='number_private_bathroom',
        ),
        migrations.AlterField(
            model_name='house',
            name='number_shared_bathroom',
            field=models.IntegerField(),
        ),
    ]
