# Generated by Django 3.2.9 on 2021-11-12 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_auto_20211112_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Type_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(default='', max_length=200)),
                ('floor_level', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('aditionnal_info', models.TextField(blank=True, default='')),
                ('number_bedroom_with_private_bathroom', models.IntegerField(default=0)),
                ('number_bedroom_without_bathroom', models.IntegerField(default=0)),
                ('number_shared_bathroom', models.IntegerField(default=0)),
                ('number_living_room', models.IntegerField(default=0)),
                ('number_kitchen', models.IntegerField(default=0)),
                ('closette', models.CharField(default='', max_length=5)),
                ('terace', models.CharField(default='', max_length=5)),
                ('balcony', models.CharField(default='', max_length=5)),
                ('rent_price', models.IntegerField(blank=True, default=0)),
                ('sale_price', models.IntegerField(blank=True, default=0)),
                ('minimum_price', models.IntegerField(blank=True, default=0)),
                ('maximum_price', models.IntegerField(blank=True, default=0)),
                ('property', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='real_estate.property')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Type_Details_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='real_estate/images/apartment/')),
                ('apartment', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='real_estate.property_type_details')),
            ],
        ),
    ]
