# Generated by Django 3.2.9 on 2021-11-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_property_type_details_property_type_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land_images2',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='real_estate/images/land/'),
        ),
        migrations.AlterField(
            model_name='property_type_details_image',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='real_estate/images/properties/'),
        ),
    ]
