# Generated by Django 3.2.9 on 2021-11-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0008_auto_20211112_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment_image',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='house',
            name='property',
        ),
        migrations.RemoveField(
            model_name='house_image',
            name='house',
        ),
        migrations.RemoveField(
            model_name='room',
            name='property',
        ),
        migrations.RemoveField(
            model_name='room_image',
            name='room',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='property',
        ),
        migrations.RemoveField(
            model_name='studio_image',
            name='studio',
        ),
        migrations.RenameField(
            model_name='property_type_details_image',
            old_name='apartment',
            new_name='property_type_detail',
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='Apartment_Image',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='House_Image',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Room_Image',
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
        migrations.DeleteModel(
            name='Studio_Image',
        ),
    ]
