# Generated by Django 3.2.9 on 2021-11-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0011_property_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_type_details',
            name='number_apartment',
            field=models.IntegerField(default=0),
        ),
    ]
