# Generated by Django 3.2.9 on 2021-11-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0012_property_type_details_number_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='done',
        ),
        migrations.AlterField(
            model_name='property',
            name='statut',
            field=models.CharField(default='In progress', max_length=25),
        ),
    ]
