# Generated by Django 3.2.9 on 2021-11-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0013_auto_20211115_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='accepted',
            field=models.BooleanField(default=0),
        ),
    ]
