# Generated by Django 3.2.9 on 2021-11-18 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0002_auto_20211112_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Success_Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('land_project_id', models.IntegerField(default=0)),
                ('property_project_id', models.IntegerField(default=0)),
                ('construction_project_id', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
