# Generated by Django 3.1.4 on 2021-10-31 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construction', '0001_initial'),
        ('real_estate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='No', max_length=5)),
                ('land_id', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('additionnal_info', models.TextField()),
                ('cart', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Construction_Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('additonnal_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Construction_Projet_Automatic_Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('additional_info', models.TextField(blank=True, default='0')),
                ('land_project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='real_estate.land_project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Construction_Projet_Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('construction_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.construction_project')),
            ],
        ),
        migrations.CreateModel(
            name='Construction_Tracker_Realisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('additonnal_info', models.TextField()),
                ('realisation_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('construction_project_tracker', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.construction_projet_tracker')),
            ],
        ),
        migrations.CreateModel(
            name='Construction_Tracker_Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Land_Projet_Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='real_estate.lands')),
                ('land_project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='real_estate.land_project')),
            ],
        ),
        migrations.CreateModel(
            name='Land_Projet_Tracker_Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(default='', max_length=500)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('additional_info', models.TextField(blank=True, default='0')),
                ('accepted', models.CharField(default='No', max_length=5)),
                ('land_region', models.CharField(default='', max_length=200)),
                ('land_adress', models.CharField(default='0', max_length=200)),
                ('land_area', models.IntegerField(default='0')),
                ('land_price', models.CharField(default=0, max_length=100)),
                ('land_plan_situation_id', models.IntegerField(default='0')),
                ('land_paper_type_id', models.IntegerField(default='0')),
                ('user_id', models.IntegerField(default=0)),
                ('land_project_tacker', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.land_projet_tracker')),
            ],
        ),
        migrations.CreateModel(
            name='Land_Projet_Tracker_Offer_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.TextField(blank=True, default='')),
                ('project_tracker_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.land_projet_tracker_offer')),
            ],
        ),
        migrations.CreateModel(
            name='Step_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('additonnal_info', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='user/images/construction/tracker/realisation/')),
                ('construction_project_tracker', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.construction_projet_tracker')),
                ('construction_tracker_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.construction_tracker_step')),
            ],
        ),
        migrations.CreateModel(
            name='Land_Projet_Tracker_Payment_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='user/images/real_estate/land_project/tracker/offers/payment/')),
                ('land_project_tracker_payment', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='user.land_projet_tracker_offer_payment')),
            ],
        ),
        migrations.CreateModel(
            name='Land_Projet_Tracker_Offer_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='user/images/real_estate/land_project/tracker/offers/')),
                ('project_tracker_offer', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='user.land_projet_tracker_offer')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('additonnal_info', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='user/images/construction/tracker/deliveries/')),
                ('construction_delivery', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.construction_delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='0', max_length=100)),
                ('adress', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, upload_to='user/images/')),
                ('birth_date', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Construction_Tracker_Sub_Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('construction_tracker_step', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.construction_tracker_step')),
            ],
        ),
        migrations.CreateModel(
            name='Construction_Tracker_Realisation_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='user/images/construction/tracker/realisation/')),
                ('construction_tracker_realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.construction_tracker_realisation')),
            ],
        ),
        migrations.AddField(
            model_name='construction_tracker_realisation',
            name='construction_tracker_sub_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.construction_tracker_sub_step'),
        ),
        migrations.CreateModel(
            name='Construction_Projet_Automatic_Counter_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='user/images/real_estate/construction/automatic_counter/')),
                ('construction_project_automatic_counter', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='user.construction_projet_automatic_counter')),
            ],
        ),
        migrations.CreateModel(
            name='Construction_Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=500)),
                ('additonnal_info', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='user/images/construction/tracker/expenses/')),
                ('construction_project_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.construction_projet_tracker')),
            ],
        ),
        migrations.CreateModel(
            name='Construction_Delivery_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='user/images/construction/tracker/deliveries/receipt/')),
                ('construction_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.construction_delivery')),
            ],
        ),
        migrations.AddField(
            model_name='construction_delivery',
            name='construction_project_tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.construction_projet_tracker'),
        ),
        migrations.AddField(
            model_name='construction_delivery',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.provider'),
        ),
        migrations.CreateModel(
            name='Cart_Payment_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='user/images/cart/cart/payment/')),
                ('cart_payment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.cart_payment')),
            ],
        ),
    ]
