# Generated by Django 3.1.4 on 2021-11-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land_projet_tracker_offer',
            name='land_region',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
