# Generated by Django 3.2.9 on 2021-11-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0014_property_accepted'),
        ('user', '0003_auto_20211112_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Projet_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='real_estate.property')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Projet_Tracker_Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(default='', max_length=500)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('additional_info', models.TextField(blank=True, default='0')),
                ('accepted', models.CharField(default='No', max_length=5)),
                ('property_region', models.CharField(default='0', max_length=200)),
                ('property_adress', models.CharField(default='0', max_length=200)),
                ('property_area', models.IntegerField(default='0')),
                ('property_price', models.CharField(default=0, max_length=100)),
                ('property_type_id', models.IntegerField(default='0')),
                ('user_id', models.IntegerField(default=0)),
                ('property_project_tacker', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.property_projet_tracker')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Projet_Tracker_Offer_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.TextField(blank=True, default='')),
                ('property_project_tracker_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.property_projet_tracker_offer')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Projet_Tracker_Payment_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='user/images/real_estate/property_project/tracker/offers/payment/')),
                ('property_project_tracker_payment', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='user.property_projet_tracker_offer_payment')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Projet_Tracker_Offer_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='user/images/real_estate/property_project/tracker/offers/')),
                ('property_project_tracker_offer', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='user.property_projet_tracker_offer')),
            ],
        ),
    ]
