# Generated by Django 3.2.9 on 2021-11-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_property_projet_tracker_property_projet_tracker_offer_property_projet_tracker_offer_image_property_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_request',
            field=models.BooleanField(default=0),
        ),
    ]
