# Generated by Django 3.2.9 on 2021-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_cart_payment_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction_tracker_realisation',
            name='realisation_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
