# Generated by Django 3.2.9 on 2021-12-23 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_architecture_project_tracker_architecture_project_tracker_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architecture_project_tracker_image',
            name='architecture_project_tracker',
        ),
        migrations.DeleteModel(
            name='Architecture_Project_Tracker',
        ),
        migrations.DeleteModel(
            name='Architecture_Project_Tracker_Image',
        ),
    ]
