# Generated by Django 3.2.9 on 2021-12-23 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_rename_construction_project_service_construction_project_construction_project_service_id'),
        ('user', '0010_auto_20211223_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture_Project_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('additonnal_info', models.TextField()),
                ('construction_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.construction_project')),
            ],
        ),
        migrations.CreateModel(
            name='Architecture_Project_Tracker_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='user/images/construction/tracker/architecture/')),
                ('architecture_project_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.architecture_project_tracker')),
            ],
        ),
    ]
