# Generated by Django 3.2.9 on 2022-06-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_architecture_project_tracker_architecture_project_tracker_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land_projet_tracker_offer',
            name='land_project_tacker',
        ),
        migrations.RemoveField(
            model_name='land_projet_tracker_offer_image',
            name='project_tracker_offer',
        ),
        migrations.RemoveField(
            model_name='land_projet_tracker_offer_payment',
            name='project_tracker_offer',
        ),
        migrations.RemoveField(
            model_name='land_projet_tracker_payment_image',
            name='land_project_tracker_payment',
        ),
        migrations.RemoveField(
            model_name='property_projet_tracker',
            name='property',
        ),
        migrations.RemoveField(
            model_name='property_projet_tracker_offer',
            name='property_project_tacker',
        ),
        migrations.RemoveField(
            model_name='property_projet_tracker_offer_image',
            name='property_project_tracker_offer',
        ),
        migrations.RemoveField(
            model_name='property_projet_tracker_offer_payment',
            name='property_project_tracker_offer',
        ),
        migrations.RemoveField(
            model_name='property_projet_tracker_payment_image',
            name='property_project_tracker_payment',
        ),
        migrations.RemoveField(
            model_name='construction_projet_automatic_counter',
            name='land_project',
        ),
        migrations.DeleteModel(
            name='Land_Projet_Tracker',
        ),
        migrations.DeleteModel(
            name='Land_Projet_Tracker_Offer',
        ),
        migrations.DeleteModel(
            name='Land_Projet_Tracker_Offer_Image',
        ),
        migrations.DeleteModel(
            name='Land_Projet_Tracker_Offer_Payment',
        ),
        migrations.DeleteModel(
            name='Land_Projet_Tracker_Payment_Image',
        ),
        migrations.DeleteModel(
            name='Property_Projet_Tracker',
        ),
        migrations.DeleteModel(
            name='Property_Projet_Tracker_Offer',
        ),
        migrations.DeleteModel(
            name='Property_Projet_Tracker_Offer_Image',
        ),
        migrations.DeleteModel(
            name='Property_Projet_Tracker_Offer_Payment',
        ),
        migrations.DeleteModel(
            name='Property_Projet_Tracker_Payment_Image',
        ),
    ]
