# Generated by Django 3.1.4 on 2021-10-31 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Construction_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=200)),
                ('adress', models.CharField(default='0', max_length=200)),
                ('area', models.IntegerField(default='0')),
                ('area_usable', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='In progress', max_length=15)),
                ('accepted', models.BooleanField(default=0)),
                ('done', models.BooleanField(default=0)),
                ('aditionnal_info', models.TextField(blank=True)),
                ('number_floor', models.IntegerField(blank=True)),
                ('construction_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='construction.construction_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Construction_floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_level', models.IntegerField()),
                ('aditionnal_info', models.TextField(blank=True, default='')),
                ('number_bedroom_with_bathroom', models.IntegerField(default=0)),
                ('number_bedroom_without_bathroom', models.IntegerField(default=0)),
                ('number_shared_bathroom', models.IntegerField()),
                ('garage', models.CharField(default='No', max_length=5)),
                ('number_living_room', models.IntegerField(default=0)),
                ('number_kitchen', models.IntegerField(default=0)),
                ('closette', models.CharField(default='No', max_length=5)),
                ('terace', models.CharField(default='No', max_length=5)),
                ('balcony', models.CharField(default='No', max_length=5)),
                ('construction_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.construction_project')),
            ],
        ),
        migrations.CreateModel(
            name='Architecture_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='construction/images/')),
                ('construction_project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='construction.construction_project')),
            ],
        ),
    ]
