# Generated by Django 3.2.9 on 2021-12-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_auto_20211112_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
    ]
