# Generated by Django 3.2.9 on 2021-12-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_construction_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction_project',
            name='construction_project_service',
            field=models.IntegerField(default='0'),
        ),
    ]
