# Generated by Django 3.2.9 on 2021-12-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_construction_project_construction_project_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='construction_project',
            old_name='construction_project_service',
            new_name='construction_project_service_id',
        ),
    ]
