# Generated by Django 3.2.9 on 2022-04-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_rename_construction_project_service_construction_project_construction_project_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction_project',
            name='construction_project_service_id',
        ),
        migrations.RemoveField(
            model_name='construction_project',
            name='done',
        ),
        migrations.RemoveField(
            model_name='construction_project',
            name='user',
        ),
        migrations.AddField(
            model_name='construction_project',
            name='client_email',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='construction_project',
            name='client_first_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='construction_project',
            name='client_last_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='construction_project',
            name='client_phone_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
