# Generated by Django 3.2.9 on 2022-06-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_auto_20220401_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('area', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
    ]
