# Generated by Django 3.2.9 on 2022-06-16 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0008_quote_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_Project_Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Quote_Project_Ouvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('mesure_unit', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quote_project_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.quote_project_step')),
            ],
        ),
        migrations.CreateModel(
            name='Quote_Project_Materiaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('mesure_unit', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quote_project_ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.quote_project_ouvrage')),
            ],
        ),
    ]
