# Generated by Django 3.2.9 on 2022-06-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0010_auto_20220616_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_project_materiaux',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default='', max_digits=19),
        ),
        migrations.AlterField(
            model_name='quote_project_ouvrage',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default='', max_digits=19),
        ),
    ]
