# Generated by Django 3.2.9 on 2022-06-16 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0011_auto_20220616_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote_project_materiaux',
            name='mesure_unit',
        ),
        migrations.RemoveField(
            model_name='quote_project_materiaux',
            name='name',
        ),
        migrations.CreateModel(
            name='Materiaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('mesure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.mesure_unit')),
            ],
        ),
        migrations.AddField(
            model_name='quote_project_materiaux',
            name='materiaux',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='construction.materiaux'),
        ),
    ]
